min-award: 50
boss-bar-time: 5.0 # in seconds

# 0 - "0"; 1 - "0.#"; 2 - "0.##"
decimal-award-format: "0"
decimal-location-format: "#"
location-update-period: 10 # in seconds
min-order-time: 10 # in minutes / after this time target would get some award depending on his survive time
max-order-time: 60 # in minutes / at this time the order will be deleted and client will be gotten his money

can-order-yourself: false
