name: KillWarrant
version: '${project.version}'
main: org.dreaght.killwarrant.KillWarrant
api-version: '1.20'
authors: [Dreaght]
description: Commission the demise of any participant.
commands:
  killer:
    description: Look at targets list, order a kill!
depend: [Vault]
