min-award: 50
boss-bar-time: 5.0 # in seconds

# 0 - "0"; 1 - "0.#"; 2 - "0.##"
decimal-award-format: "0"
decimal-location-format: "#"
location-update-period: 10 # in seconds
max-order-time: 60 # in minutes / at this time the order will be deleted and client will be gotten his money

can-order-yourself: false

# will the reward for the killer decrease with the time the warrant expires
award-decrease: true
