name: KillWarrant
version: 1.0
main: org.dreaght.killwarrant.KillWarrant
authors: [Dreaght]
description: Commission the demise of any participant.
commands:
  killer:
    description: Look at targets list, order a kill!
depend: [Vault]
api-version: 1.13
