name: KillWarrant
version: ${project.version}
main: org.dreaght.killwarrant.KillWarrant
authors: [Dreaght]
description: ${project.description}
commands:
  killer:
    description: Look at targets list, order a kill!
depend: [Vault]
api-version: 1.13
